# Generated by Django 5.1.2 on 2024-10-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selections', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaskitem',
            name='task_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskitem'),
        ),
        migrations.AddField(
            model_name='testtaskitem',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask'),
        ),
    ]
