# Generated by Django 5.1.2 on 2024-10-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_company_description_company_description_and_more'),
        ('resumes', '0004_alter_job_options_alter_resume_options_and_more'),
        ('selections', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyselection',
            options={'verbose_name': 'Отбор компании', 'verbose_name_plural': 'Отборы компаний'},
        ),
        migrations.AlterModelOptions(
            name='testtaskitem',
            options={'verbose_name': 'Элемент задания теста', 'verbose_name_plural': 'Элементы задания теста'},
        ),
        migrations.AlterField(
            model_name='companyselection',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.interviewer', verbose_name='Интервьюер'),
        ),
        migrations.AlterField(
            model_name='companyselection',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='companyselection',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принят', 'Принят'), ('Отклонен', 'Отклонен')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testtaskitem',
            name='candidate_answer',
            field=models.TextField(verbose_name='Ответ кандидата'),
        ),
        migrations.AlterField(
            model_name='testtaskitem',
            name='interviewer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий интервьюера'),
        ),
        migrations.AlterField(
            model_name='testtaskitem',
            name='task_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskitem', verbose_name='Элемент задания'),
        ),
        migrations.AlterField(
            model_name='testtaskitem',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='Тестовое задание'),
        ),
    ]
