# Generated by Django 5.1.2 on 2024-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Запланировано', 'Запланировано'), ('Завершено', 'Завершено'), ('Отклонено', 'Отклонено')], max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hard_skills_rate', models.IntegerField(blank=True, null=True)),
                ('soft_skills_rate', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=20)),
                ('recording_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.TextField()),
            ],
        ),
    ]
