# Generated by Django 5.1.2 on 2024-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills_rate', models.IntegerField()),
                ('soft_skills_rate', models.IntegerField()),
                ('final_feedback', models.TextField()),
                ('overall_result', models.CharField(choices=[('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
