# Generated by Django 5.1.2 on 2024-10-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_interviewevaluation_evaluation_date_and_more'),
        ('interviews', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewevaluation',
            options={'verbose_name': 'Оценка интервью', 'verbose_name_plural': 'Оценки интервью'},
        ),
        migrations.AlterModelOptions(
            name='testevaluation',
            options={'verbose_name': 'Оценка теста', 'verbose_name_plural': 'Оценки тестов'},
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='evaluation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='final_feedback',
            field=models.TextField(verbose_name='Финальная обратная связь'),
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='hard_skills_rate',
            field=models.IntegerField(verbose_name='Оценка хард скиллов'),
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview', verbose_name='Интервью'),
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='overall_result',
            field=models.CharField(choices=[('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=20, verbose_name='Общий результат'),
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='soft_skills_rate',
            field=models.IntegerField(verbose_name='Оценка софт скиллов'),
        ),
        migrations.AlterField(
            model_name='testevaluation',
            name='evaluation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='testevaluation',
            name='feedback',
            field=models.TextField(verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='testevaluation',
            name='result',
            field=models.CharField(choices=[('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=20, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='testevaluation',
            name='test_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='Тестовое задание'),
        ),
    ]
