# Generated by Django 5.1.2 on 2024-10-24 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='interviewer',
            options={'verbose_name': 'Интервьюер', 'verbose_name_plural': 'Интервьюеры'},
        ),
        migrations.AddField(
            model_name='company',
            name='established_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
    ]
