# Generated by Django 5.1.2 on 2024-10-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_interviewer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
    ]
