# Generated by Django 5.1.2 on 2024-10-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_skill_remove_resume_skills_resume_skills'),
        ('users', '0002_alter_candidate_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.candidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desired_position',
            field=models.CharField(max_length=255, verbose_name='Желаемая должность'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desired_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Желаемая зарплата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(related_name='resumes', to='resumes.skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание навыка'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название навыка'),
        ),
    ]
