# Generated by Django 5.1.3 on 2024-11-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('complexity', models.IntegerField(verbose_name='Сложность')),
                ('task_condition', models.TextField(verbose_name='Условие задания')),
            ],
            options={
                'verbose_name': 'Элемент задания',
                'verbose_name_plural': 'Элементы задания',
            },
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('task_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskitem', verbose_name='Элемент задания')),
            ],
            options={
                'verbose_name': 'Задание с открытым ответом',
                'verbose_name_plural': 'Задания с открытыми ответами',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct_answer', models.BooleanField(verbose_name='Правильный ответ')),
                ('task_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskitem', verbose_name='Элемент задания')),
            ],
            options={
                'verbose_name': 'Задание с выбором ответа',
                'verbose_name_plural': 'Задания с выбором ответа',
            },
        ),
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, verbose_name='Язык программирования')),
                ('is_code_run', models.BooleanField(default=False, verbose_name='Код выполнен')),
                ('code_snippet', models.TextField(verbose_name='Код')),
                ('task_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskitem', verbose_name='Элемент задания')),
            ],
            options={
                'verbose_name': 'Задание с написанием кода',
                'verbose_name_plural': 'Задания с написанием кода',
            },
        ),
    ]
